all:
	latexmk -pdf 
	-mv *.aux build
	-mv *.blg build
	-mv *.fdb_latexmk build
	-mv *.idx build
	-mv *.ilg build
	-mv *.ind build
	-mv *.log build
	-mv *.out build
	-mv *.pdf build
	-mv *.toc build


	

clean:
	-rm build/*
